package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaMensagem generated by hbm2java
 */
public class TaMensagem  implements java.io.Serializable {


     private Integer idtMensagem;
     private TbPrestador tbPrestador;
     private TbUsuario tbUsuario;
     private String mensagens;
     private Date dataHoraMensagem;

    public TaMensagem() {
    }

    public TaMensagem(TbPrestador tbPrestador, TbUsuario tbUsuario, String mensagens, Date dataHoraMensagem) {
       this.tbPrestador = tbPrestador;
       this.tbUsuario = tbUsuario;
       this.mensagens = mensagens;
       this.dataHoraMensagem = dataHoraMensagem;
    }
   
    public Integer getIdtMensagem() {
        return this.idtMensagem;
    }
    
    public void setIdtMensagem(Integer idtMensagem) {
        this.idtMensagem = idtMensagem;
    }
    public TbPrestador getTbPrestador() {
        return this.tbPrestador;
    }
    
    public void setTbPrestador(TbPrestador tbPrestador) {
        this.tbPrestador = tbPrestador;
    }
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    public String getMensagens() {
        return this.mensagens;
    }
    
    public void setMensagens(String mensagens) {
        this.mensagens = mensagens;
    }
    public Date getDataHoraMensagem() {
        return this.dataHoraMensagem;
    }
    
    public void setDataHoraMensagem(Date dataHoraMensagem) {
        this.dataHoraMensagem = dataHoraMensagem;
    }




}


