package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TtAssinatura generated by hbm2java
 */
public class TtAssinatura  implements java.io.Serializable {


     private Integer idtAssinatura;
     private TtTipoPagamento ttTipoPagamento;
     private Date dtAssAssinatura;
     private Date prazoAssinatura;
     private Set<TtPagamento> ttPagamentos = new HashSet<TtPagamento>(0);

    public TtAssinatura() {
    }

	
    public TtAssinatura(TtTipoPagamento ttTipoPagamento, Date dtAssAssinatura, Date prazoAssinatura) {
        this.ttTipoPagamento = ttTipoPagamento;
        this.dtAssAssinatura = dtAssAssinatura;
        this.prazoAssinatura = prazoAssinatura;
    }
    public TtAssinatura(TtTipoPagamento ttTipoPagamento, Date dtAssAssinatura, Date prazoAssinatura, Set<TtPagamento> ttPagamentos) {
       this.ttTipoPagamento = ttTipoPagamento;
       this.dtAssAssinatura = dtAssAssinatura;
       this.prazoAssinatura = prazoAssinatura;
       this.ttPagamentos = ttPagamentos;
    }
   
    public Integer getIdtAssinatura() {
        return this.idtAssinatura;
    }
    
    public void setIdtAssinatura(Integer idtAssinatura) {
        this.idtAssinatura = idtAssinatura;
    }
    public TtTipoPagamento getTtTipoPagamento() {
        return this.ttTipoPagamento;
    }
    
    public void setTtTipoPagamento(TtTipoPagamento ttTipoPagamento) {
        this.ttTipoPagamento = ttTipoPagamento;
    }
    public Date getDtAssAssinatura() {
        return this.dtAssAssinatura;
    }
    
    public void setDtAssAssinatura(Date dtAssAssinatura) {
        this.dtAssAssinatura = dtAssAssinatura;
    }
    public Date getPrazoAssinatura() {
        return this.prazoAssinatura;
    }
    
    public void setPrazoAssinatura(Date prazoAssinatura) {
        this.prazoAssinatura = prazoAssinatura;
    }
    public Set<TtPagamento> getTtPagamentos() {
        return this.ttPagamentos;
    }
    
    public void setTtPagamentos(Set<TtPagamento> ttPagamentos) {
        this.ttPagamentos = ttPagamentos;
    }




}


