package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TtCategoriaServico generated by hbm2java
 */
public class TtCategoriaServico  implements java.io.Serializable {


     private Integer idtCategoriaServico;
     private String categoriaServico;
     private Set<TtTipoServico> ttTipoServicos = new HashSet<TtTipoServico>(0);

    public TtCategoriaServico() {
    }

	
    public TtCategoriaServico(String categoriaServico) {
        this.categoriaServico = categoriaServico;
    }
    public TtCategoriaServico(String categoriaServico, Set<TtTipoServico> ttTipoServicos) {
       this.categoriaServico = categoriaServico;
       this.ttTipoServicos = ttTipoServicos;
    }
   
    public Integer getIdtCategoriaServico() {
        return this.idtCategoriaServico;
    }
    
    public void setIdtCategoriaServico(Integer idtCategoriaServico) {
        this.idtCategoriaServico = idtCategoriaServico;
    }
    public String getCategoriaServico() {
        return this.categoriaServico;
    }
    
    public void setCategoriaServico(String categoriaServico) {
        this.categoriaServico = categoriaServico;
    }
    public Set<TtTipoServico> getTtTipoServicos() {
        return this.ttTipoServicos;
    }
    
    public void setTtTipoServicos(Set<TtTipoServico> ttTipoServicos) {
        this.ttTipoServicos = ttTipoServicos;
    }




}


