package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TtPagamento generated by hbm2java
 */
public class TtPagamento  implements java.io.Serializable {


     private Integer idtPagamento;
     private TtAssinatura ttAssinatura;
     private String periodoPagamento;
     private BigDecimal vlrPagamento;

    public TtPagamento() {
    }

    public TtPagamento(TtAssinatura ttAssinatura, String periodoPagamento, BigDecimal vlrPagamento) {
       this.ttAssinatura = ttAssinatura;
       this.periodoPagamento = periodoPagamento;
       this.vlrPagamento = vlrPagamento;
    }
   
    public Integer getIdtPagamento() {
        return this.idtPagamento;
    }
    
    public void setIdtPagamento(Integer idtPagamento) {
        this.idtPagamento = idtPagamento;
    }
    public TtAssinatura getTtAssinatura() {
        return this.ttAssinatura;
    }
    
    public void setTtAssinatura(TtAssinatura ttAssinatura) {
        this.ttAssinatura = ttAssinatura;
    }
    public String getPeriodoPagamento() {
        return this.periodoPagamento;
    }
    
    public void setPeriodoPagamento(String periodoPagamento) {
        this.periodoPagamento = periodoPagamento;
    }
    public BigDecimal getVlrPagamento() {
        return this.vlrPagamento;
    }
    
    public void setVlrPagamento(BigDecimal vlrPagamento) {
        this.vlrPagamento = vlrPagamento;
    }




}


