package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TtTipoPagamento generated by hbm2java
 */
public class TtTipoPagamento  implements java.io.Serializable {


     private Integer idtTipoPagamento;
     private TbPrestador tbPrestador;
     private String tipoPagamento;
     private Set<TtAssinatura> ttAssinaturas = new HashSet<TtAssinatura>(0);

    public TtTipoPagamento() {
    }

	
    public TtTipoPagamento(TbPrestador tbPrestador, String tipoPagamento) {
        this.tbPrestador = tbPrestador;
        this.tipoPagamento = tipoPagamento;
    }
    public TtTipoPagamento(TbPrestador tbPrestador, String tipoPagamento, Set<TtAssinatura> ttAssinaturas) {
       this.tbPrestador = tbPrestador;
       this.tipoPagamento = tipoPagamento;
       this.ttAssinaturas = ttAssinaturas;
    }
   
    public Integer getIdtTipoPagamento() {
        return this.idtTipoPagamento;
    }
    
    public void setIdtTipoPagamento(Integer idtTipoPagamento) {
        this.idtTipoPagamento = idtTipoPagamento;
    }
    public TbPrestador getTbPrestador() {
        return this.tbPrestador;
    }
    
    public void setTbPrestador(TbPrestador tbPrestador) {
        this.tbPrestador = tbPrestador;
    }
    public String getTipoPagamento() {
        return this.tipoPagamento;
    }
    
    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }
    public Set<TtAssinatura> getTtAssinaturas() {
        return this.ttAssinaturas;
    }
    
    public void setTtAssinaturas(Set<TtAssinatura> ttAssinaturas) {
        this.ttAssinaturas = ttAssinaturas;
    }




}


