package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TtTipoServico generated by hbm2java
 */
public class TtTipoServico  implements java.io.Serializable {


     private Integer idtTipoServico;
     private TtCategoriaServico ttCategoriaServico;
     private String nmeTipoServico;
     private Set<TbServico> tbServicos = new HashSet<TbServico>(0);

    public TtTipoServico() {
    }

	
    public TtTipoServico(TtCategoriaServico ttCategoriaServico, String nmeTipoServico) {
        this.ttCategoriaServico = ttCategoriaServico;
        this.nmeTipoServico = nmeTipoServico;
    }
    public TtTipoServico(TtCategoriaServico ttCategoriaServico, String nmeTipoServico, Set<TbServico> tbServicos) {
       this.ttCategoriaServico = ttCategoriaServico;
       this.nmeTipoServico = nmeTipoServico;
       this.tbServicos = tbServicos;
    }
   
    public Integer getIdtTipoServico() {
        return this.idtTipoServico;
    }
    
    public void setIdtTipoServico(Integer idtTipoServico) {
        this.idtTipoServico = idtTipoServico;
    }
    public TtCategoriaServico getTtCategoriaServico() {
        return this.ttCategoriaServico;
    }
    
    public void setTtCategoriaServico(TtCategoriaServico ttCategoriaServico) {
        this.ttCategoriaServico = ttCategoriaServico;
    }
    public String getNmeTipoServico() {
        return this.nmeTipoServico;
    }
    
    public void setNmeTipoServico(String nmeTipoServico) {
        this.nmeTipoServico = nmeTipoServico;
    }
    public Set<TbServico> getTbServicos() {
        return this.tbServicos;
    }
    
    public void setTbServicos(Set<TbServico> tbServicos) {
        this.tbServicos = tbServicos;
    }




}


