package br.uniceub.fsw.model;
// Generated 28/06/2017 20:26:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TtTipoPrestador generated by hbm2java
 */
public class TtTipoPrestador  implements java.io.Serializable {


     private Integer idtTipoPrestador;
     private String tipoPrestador;
     private Set<TbPrestador> tbPrestadors = new HashSet<TbPrestador>(0);

    public TtTipoPrestador() {
    }

	
    public TtTipoPrestador(String tipoPrestador) {
        this.tipoPrestador = tipoPrestador;
    }
    public TtTipoPrestador(String tipoPrestador, Set<TbPrestador> tbPrestadors) {
       this.tipoPrestador = tipoPrestador;
       this.tbPrestadors = tbPrestadors;
    }
   
    public Integer getIdtTipoPrestador() {
        return this.idtTipoPrestador;
    }
    
    public void setIdtTipoPrestador(Integer idtTipoPrestador) {
        this.idtTipoPrestador = idtTipoPrestador;
    }
    public String getTipoPrestador() {
        return this.tipoPrestador;
    }
    
    public void setTipoPrestador(String tipoPrestador) {
        this.tipoPrestador = tipoPrestador;
    }
    public Set<TbPrestador> getTbPrestadors() {
        return this.tbPrestadors;
    }
    
    public void setTbPrestadors(Set<TbPrestador> tbPrestadors) {
        this.tbPrestadors = tbPrestadors;
    }




}


